name: Bonjour
on:
  - push
jobs:
  run_maven:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - run: mvn -v
    - run: mvn effective:pom