name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - run: mvn package
    - uses: actions/upload-artifact@v2
      with:
        name: menu-server_jar
        path: ../target/menu-server.jar